import { useRef, useState } from "react";
import { ArrowRight, Check, Download, FileText, FileUp, LoaderCircle, ShieldCheck, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import { analysisService } from "@/services/analysisService";
import { uploadService } from "@/services/uploadService";
import { reportService } from "@/services/reportService";
import { getErrorMessage } from "@/lib/api";
import type { Analysis as AnalysisType } from "@/types/analysis";

const examples = ["Increase UPI transaction limit for retail customers", "Modify KYC workflow for new account onboarding", "Add an RBI compliance rule for loan disbursement"];
const formats = new Set(["pdf", "docx", "txt", "csv", "xlsx"]);
const tones: Record<string, string> = { Low: "bg-emerald-50 text-emerald-700", Medium: "bg-amber-50 text-amber-700", High: "bg-orange-50 text-orange-700", Critical: "bg-rose-50 text-rose-700" };

function Report({ analysis }: { analysis: AnalysisType }) {
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState("");
  const download = async () => {
    setDownloading(true); setError("");
    try { await reportService.download(analysis.id); } catch (e) { setError(getErrorMessage(e)); } finally { setDownloading(false); }
  };
  const cards: [string, string[]][] = [["Business impact", analysis.businessImpact], ["Technical notes", analysis.technicalImpact], ["Affected APIs", analysis.affectedApis || []], ["Affected database tables", analysis.affectedDatabaseTables || []], ["Compliance suggestions", analysis.complianceSuggestions || []], ["Approval workflow", analysis.approvalWorkflow || []], ["Development checklist", analysis.developmentChecklist], ["Testing checklist", analysis.testingChecklist], ["Deployment checklist", analysis.deploymentChecklist], ["Recommendations", analysis.recommendations]];
  return <section className="border-t border-slate-200 bg-white px-5 py-8 md:px-10">
    <div className="grid gap-6 border-b border-slate-200 pb-7 md:grid-cols-[120px_1fr_auto] md:items-center">
      <div className="grid h-28 w-28 place-content-center rounded-full border-8 border-cyan-500 bg-slate-50 text-center"><b className="text-3xl text-slate-950">{analysis.riskScore}</b><span className="text-[10px] font-bold tracking-wider text-slate-500">RISK SCORE</span></div>
      <div><p className="font-mono text-xs font-bold tracking-wider text-blue-700">// ANALYSIS COMPLETE · BANKING RULE ENGINE</p><h3 className="mt-2 text-xl font-bold text-slate-950">{analysis.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{analysis.executiveSummary || analysis.summary}</p><span className={`mt-3 inline-flex rounded-full px-3 py-1 text-xs font-bold ${tones[analysis.riskLevel]}`}>{analysis.riskLevel.toUpperCase()} RISK</span></div>
      <div className="text-left md:text-right"><b className="text-3xl text-blue-700">{analysis.confidenceScore}%</b><p className="text-[11px] font-bold tracking-wider text-slate-500">CONFIDENCE</p><button onClick={download} disabled={downloading} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-800 hover:border-blue-600 disabled:opacity-60">{downloading ? <LoaderCircle size={14} className="animate-spin" /> : <Download size={14} />}{downloading ? "Preparing…" : "Download PDF report"}</button>{error && <p className="mt-2 text-xs text-rose-600">{error}</p>}</div>
    </div>
    <div className="mt-6"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Impacted modules & teams</p><div className="mt-3 flex flex-wrap gap-2">{analysis.impactedModules.map(item => <span key={item} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 font-mono text-xs text-slate-700">{item}</span>)}{(analysis.affectedTeams || []).map(item => <span key={item} className="rounded-lg border border-cyan-100 bg-cyan-50 px-3 py-2 font-mono text-xs text-cyan-800">{item}</span>)}</div></div>
    <div className="mt-7 grid gap-4 md:grid-cols-2"><article className="rounded-xl border border-slate-200 p-5"><h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">Risk heatmap</h4><div className="mt-4 space-y-3">{Object.entries(analysis.riskFactors || {}).map(([factor, level]) => <div key={factor} className="flex items-center justify-between text-sm"><span className="text-slate-700">{factor}</span><span className={`rounded-full px-2 py-1 text-xs font-bold ${level === "High" || level === "Elevated" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{level}</span></div>)}</div></article><article className="rounded-xl border border-slate-200 p-5"><h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">Dependency graph</h4><div className="mt-4 space-y-3">{Object.entries(analysis.dependencyGraph || {}).map(([module, dependencies]) => <div key={module} className="text-sm"><b className="text-slate-800">{module}</b><p className="mt-1 text-slate-500">→ {dependencies}</p></div>)}</div></article></div>
    <div className="mt-7 grid gap-4 md:grid-cols-2">{cards.map(([title, items]) => <article key={title} className="rounded-xl border border-slate-200 p-5"><h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">{title}</h4><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{items.map(item => <li key={item} className="flex gap-2"><Check size={15} className="mt-1 shrink-0 text-cyan-600" />{item}</li>)}</ul></article>)}</div>
  </section>;
}

export default function Analysis() {
  const initial = (useLocation().state as { analysis?: AnalysisType } | null)?.analysis;
  const input = useRef<HTMLInputElement>(null);
  const [text, setText] = useState(""); const [file, setFile] = useState<File | null>(null);
  const [analysis, setAnalysis] = useState<AnalysisType | undefined>(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const choose = (selected?: File) => {
    if (!selected) return;
    const extension = selected.name.split(".").pop()?.toLowerCase() || "";
    if (!formats.has(extension)) { setError("Upload a PDF, DOCX, TXT, CSV or XLSX file."); return; }
    if (selected.size > 20 * 1024 * 1024) { setError("The file must be 20 MB or smaller."); return; }
    setFile(selected); setError("");
  };
  const run = async () => {
    if (!file && !text.trim()) { setError("Upload a document or describe the banking change."); return; }
    setBusy(true); setError("");
    try { const result = file ? (await uploadService.upload(file)).analysis : await analysisService.analyse(text); setAnalysis(result); }
    catch (e) { setError(getErrorMessage(e)); } finally { setBusy(false); }
  };
  return <main className="min-h-screen bg-white text-slate-950">
    <nav className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex h-[68px] max-w-6xl items-center justify-between px-5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-content-center rounded-lg bg-gradient-to-br from-blue-700 to-cyan-500 text-xs text-white"><ShieldCheck size={16}/></span><div><b className="tracking-wide">AUREX</b><p className="text-[10px] text-slate-500">Banking Change Intelligence</p></div></div><a href="#analyze" className="rounded-lg bg-gradient-to-r from-blue-700 to-cyan-500 px-4 py-2 text-sm font-bold text-white">Try live analysis</a></div></nav>
    <section className="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-[1.1fr_.9fr] md:py-24"><div><p className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-3 py-1.5 font-mono text-xs text-blue-700"><span className="h-1.5 w-1.5 rounded-full bg-cyan-500"/>RULE-ENGINE POWERED</p><h1 className="mt-5 text-4xl font-bold leading-tight tracking-tight md:text-5xl">Understand every banking change <span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">before you ship it.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">Upload a banking document or describe a request. AUREX detects impacted modules, risk and delivery controls, then generates a report you can download as PDF.</p><a href="#analyze" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-blue-700 to-cyan-500 px-5 py-3 font-bold text-white">Analyze a request <ArrowRight size={17}/></a></div><div className="grid content-center gap-4"><div className="rounded-xl border border-slate-200 p-5 shadow-xl shadow-blue-950/5"><p className="text-xs text-slate-500">Risk level</p><b className="mt-1 text-2xl">High <span className="rounded-full bg-rose-50 px-2 py-1 text-xs text-rose-700">RISK</span></b></div><div className="ml-8 rounded-xl border border-slate-200 p-5 shadow-xl shadow-blue-950/5"><p className="text-xs text-slate-500">Impacted modules</p><b className="mt-1 text-lg">Payments · Compliance</b></div><div className="rounded-xl border border-slate-200 p-5 shadow-xl shadow-blue-950/5"><p className="text-xs text-slate-500">Generated report</p><b className="mt-1 text-lg">PDF ready to download</b></div></div></section>
    <section id="analyze" className="border-y border-slate-200 bg-slate-50 py-16"><div className="mx-auto max-w-6xl px-5"><div className="mx-auto mb-9 max-w-2xl text-center"><p className="font-mono text-xs font-bold text-blue-700">// LIVE ANALYSIS</p><h2 className="mt-3 text-3xl font-bold">Upload, analyze and generate your report</h2><p className="mt-3 text-slate-600">PDF upload and text analysis are both saved to your AUREX account.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl shadow-slate-900/10"><div className="p-5 md:p-8"><input ref={input} hidden type="file" accept=".pdf,.docx,.txt,.csv,.xlsx" onChange={e => choose(e.target.files?.[0])}/><div onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); choose(e.dataTransfer.files[0]); }} onClick={() => input.current?.click()} className="cursor-pointer rounded-xl border-2 border-dashed border-slate-300 p-7 text-center transition hover:border-blue-600 hover:bg-blue-50"><FileUp className="mx-auto text-slate-500"/><p className="mt-3 text-sm text-slate-600"><b className="text-slate-900">Drop a document</b> or click to browse</p><p className="mt-1 font-mono text-[11px] text-slate-500">PDF, DOCX, TXT, CSV or XLSX · maximum 20 MB</p></div>{file && <div className="mt-4 flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm"><FileText className="text-blue-700"/><span className="flex-1 truncate font-medium">{file.name}</span><button onClick={() => setFile(null)} aria-label="Remove file"><X size={17}/></button></div>}<label className="mt-6 block text-sm font-semibold text-slate-700">Banking change request</label><textarea value={text} onChange={e => setText(e.target.value)} placeholder="e.g. Increase UPI transaction limit for retail customers" className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 p-4 text-sm outline-none focus:border-blue-600"/><div className="mt-3 flex flex-wrap gap-2">{examples.map(example => <button key={example} onClick={() => setText(example)} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs text-slate-600 hover:border-blue-600">{example}</button>)}</div><div className="mt-5 flex justify-end"><button onClick={run} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-blue-700 to-cyan-500 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? <LoaderCircle size={16} className="animate-spin"/> : <ShieldCheck size={16}/>} {busy ? "Analyzing…" : file ? "Upload & analyze" : "Analyze request"}<ArrowRight size={16}/></button></div>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}</div>{analysis && <Report analysis={analysis}/>}</div></div></section>
  </main>;
}
