import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, ArrowUpRight, BarChart3, BrainCircuit, CheckCircle2, CircleAlert, ClipboardCheck, ShieldCheck, TimerReset } from "lucide-react";
import DashboardLayout from "@/layouts/DashboardLayout";
import { analysisService } from "@/services/analysisService";
import type { Analysis } from "@/types/analysis";

const colors: Record<string, string> = { Low: "bg-emerald-400", Medium: "bg-amber-400", High: "bg-orange-400", Critical: "bg-rose-400" };
function Metric({ label, value, caption, icon: Icon }: { label: string; value: string; caption: string; icon: typeof Activity }) { return <div className="aurex-panel p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{caption}</p></div><div className="rounded-xl bg-cyan-400/10 p-3 text-cyan-300"><Icon size={20}/></div></div></div>; }
export default function Dashboard() {
  const [rows, setRows] = useState<Analysis[]>([]); const navigate = useNavigate();
  useEffect(() => { analysisService.history().then(setRows).catch(() => setRows([])); }, []);
  const stats = useMemo(() => {
    const dist = { Low: 0, Medium: 0, High: 0, Critical: 0 }; rows.forEach(x => dist[x.riskLevel]++);
    const today = new Date().toDateString(); const teams = rows.flatMap(x => x.affectedTeams || []); const teamCounts = teams.reduce<Record<string, number>>((all, team) => ({ ...all, [team]: (all[team] || 0) + 1 }), {});
    return { dist, today: rows.filter(x => new Date(x.createdAt).toDateString() === today).length, avg: rows.length ? Math.round(rows.reduce((n, x) => n + x.riskScore, 0) / rows.length) : 0, modules: [...new Set(rows.flatMap(x => x.impactedModules || []))].slice(0, 6), teams: Object.entries(teamCounts).sort((a, b) => b[1] - a[1]).slice(0, 6) };
  }, [rows]);
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="aurex-eyebrow">Enterprise portfolio overview</p><h1 className="mt-2 text-3xl font-semibold text-white">Banking change intelligence</h1><p className="mt-2 text-slate-400">Risk, ownership and delivery readiness across your secured workspace.</p></div><button onClick={() => navigate("/analysis")} className="aurex-button"><BrainCircuit size={17}/>New analysis<ArrowUpRight size={17}/></button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total requests" value={String(rows.length)} caption="Saved banking assessments" icon={ClipboardCheck}/><Metric label="Critical requests" value={String(stats.dist.Critical)} caption="Immediate governance attention" icon={CircleAlert}/><Metric label="High risk" value={String(stats.dist.High)} caption="Requires controlled delivery" icon={ShieldCheck}/><Metric label="Medium risk" value={String(stats.dist.Medium)} caption="Standard governance required" icon={Activity}/><Metric label="Low risk" value={String(stats.dist.Low)} caption="Lower delivery complexity" icon={CheckCircle2}/><Metric label="Today's requests" value={String(stats.today)} caption="Created today" icon={TimerReset}/><Metric label="Completed analyses" value={String(rows.length)} caption="Persisted completed assessments" icon={CheckCircle2}/></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-5"><section className="aurex-panel p-6 lg:col-span-2"><div className="flex items-center gap-2"><BarChart3 size={18} className="text-cyan-300"/><h2 className="font-semibold text-white">Risk distribution</h2></div><div className="mt-6 space-y-4">{Object.entries(stats.dist).map(([level, count]) => { const width = rows.length ? Math.max(6, count / rows.length * 100) : 6; return <div key={level}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-300">{level}</span><span className="text-slate-500">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${colors[level]}`} style={{ width: `${width}%` }}/></div></div>; })}</div></section><section className="aurex-panel p-6 lg:col-span-3"><h2 className="font-semibold text-white">Recent requests</h2><div className="mt-4 divide-y divide-slate-800">{rows.slice(0, 5).map(a => <button key={a.id} onClick={() => navigate("/analysis", { state: { analysis: a } })} className="flex w-full items-center justify-between gap-4 py-4 text-left"><div className="min-w-0"><p className="truncate text-sm font-medium text-white">{a.title}</p><p className="mt-1 text-xs text-slate-500">{new Date(a.createdAt).toLocaleDateString()} · {(a.impactedModules || []).slice(0, 2).join(" · ")}</p></div><span className="text-sm text-cyan-300">{a.riskScore}</span></button>)}{!rows.length && <p className="py-10 text-center text-sm text-slate-500">Run your first analysis to populate the portfolio.</p>}</div></section></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="aurex-panel p-6"><h2 className="font-semibold text-white">Department distribution</h2><div className="mt-4 space-y-3">{stats.teams.length ? stats.teams.map(([team, count]) => <div key={team} className="flex items-center justify-between rounded-lg bg-slate-800/70 px-3 py-2 text-sm"><span className="text-slate-300">{team}</span><span className="font-semibold text-cyan-300">{count}</span></div>) : <p className="text-sm text-slate-500">Teams will be calculated from new analyses.</p>}</div></section><section className="aurex-panel p-6"><h2 className="font-semibold text-white">Top impacted modules</h2><div className="mt-4 flex flex-wrap gap-2">{stats.modules.length ? stats.modules.map(x => <span key={x} className="rounded-lg bg-slate-800 px-3 py-2 text-sm text-slate-300">{x}</span>) : <span className="text-sm text-slate-500">Modules will emerge from your analysed change requests.</span>}</div><p className="mt-6 text-xs text-slate-500">Average risk: {rows.length ? `${stats.avg}/100` : "No assessments yet"}</p></section></div>
  </div></DashboardLayout>;
}
