CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(320) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    request_text VARCHAR(5000) NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    confidence_score INTEGER NOT NULL,
    title VARCHAR(1200) NOT NULL,
    summary VARCHAR(4000) NOT NULL,
    analysis_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_change_requests_risk_score CHECK (risk_score BETWEEN 0 AND 100),
    CONSTRAINT chk_change_requests_confidence_score CHECK (confidence_score BETWEEN 0 AND 100),
    CONSTRAINT chk_change_requests_risk_level CHECK (risk_level IN ('Low', 'Medium', 'High', 'Critical')),
    CONSTRAINT fk_change_requests_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_change_requests_user_created_at
    ON change_requests (user_id, created_at DESC);

CREATE INDEX idx_change_requests_user_risk_level
    ON change_requests (user_id, risk_level);
