package com.aurex.aurexbackend.service;

import org.springframework.stereotype.Component;
import java.util.*;
import java.util.regex.Pattern;

/** Explainable offline banking intelligence engine with domain, control and delivery reasoning. */
@Component
public class BankingRuleEngine {
    private record DomainRule(String domain, int weight, Set<String> signals, List<String> modules, List<String> teams, String reason, String recommendation) {}
    private final List<DomainRule> rules = List.of(
        rule("Payments & settlement",18,"neft,rtgs,imps,upi,swift,payment,payment gateway,settlement,reversal,beneficiary","NEFT / RTGS / IMPS / UPI Processing,Transaction Validation,Settlement Service,Payment Gateway,Core Banking,Reconciliation,Notification Service,Audit Logs","Backend Team,QA Team,Operations Team,Finance/Reconciliation Team,Security Team","Payment-rail changes can affect high-volume, time-sensitive transactions and settlement accuracy.","Validate limits, idempotency, reversal paths, settlement cut-offs and reconciliation controls."),
        rule("Regulatory compliance",22,"kyc,aml,rbi,npci,compliance,audit,gst,tax,regulatory,sanctions","Compliance Engine,KYC/AML Service,Audit Logs,Reporting Service,Customer Profile","Compliance Team,Legal Team,Backend Team,QA Team,Business Team","Regulatory obligations require traceable evidence, policy review and controlled approval.","Obtain formal compliance approval and retain policy, test and release evidence."),
        rule("Identity, fraud & security",25,"security,encryption,authentication,authorization,otp,pin,fraud,mfa,access control,credential","Authentication Service,Authorization Service,Fraud Detection,Security Gateway,Audit Logs,Notification Service","Security Team,Backend Team,QA Team,DevOps Team,Compliance Team","Identity and security-control changes can expose customer data or create fraud risk.","Complete threat modelling, least-privilege review, penetration testing and security sign-off."),
        rule("Lending, cards & deposits",16,"loan,mortgage,interest,credit card,debit card,emi,insurance,fixed deposit,recurring deposit,deposit","Loan Service,Card Management,Interest Calculation,Account Service,Risk Engine,Customer Profile","Business Team,Backend Team,Database Team,QA Team,Operations Team","Product and pricing changes affect balances, eligibility, customer communication and financial calculations.","Validate product rules, pricing calculations, eligibility, statements and customer communication."),
        rule("Customer channels",14,"mobile banking,internet banking,atm,branch,account opening,customer profile,notification,sms,email","Mobile Banking,Internet Banking,ATM Switch,Branch Operations,Customer Profile,Notification Service","Frontend Team,Backend Team,QA Team,Operations Team,Business Team","Channel changes may alter customer journeys, accessibility and service availability.","Review user journeys, accessibility, customer communication and channel fallback behaviour."),
        rule("Core platform & data",15,"cbs,core banking,database,microservice,api,api gateway,caching,logging,performance,scalability,queue,scheduler","Core Banking,API Gateway,Database,Microservices,Cache,Logging & Monitoring,Workflow Engine","Backend Team,Database Team,DevOps Team,QA Team,Architecture Team","Platform changes create compatibility, performance, availability and data-integrity risks.","Use backward-compatible contracts, migration rehearsal, observability, capacity checks and a tested rollback."),
        rule("Limits & transactions",18,"transaction limit,limit,balance,transfer,withdrawal,deposit limit,daily limit,threshold","Limit Validation,Transaction Validation,Account Service,Customer Profile,Audit Logs,Notification Service","Backend Team,QA Team,Compliance Team,Operations Team,Business Team","Limit changes influence customer outcomes and may require approval thresholds and disclosures.","Confirm limit configuration, approval thresholds, exception handling, disclosures and reconciliation."),
        rule("Reporting & operations",12,"report,reconciliation,audit log,branch operations,operations,statement,monitoring,alert","Reporting Service,Reconciliation,Audit Logs,Branch Operations,Logging & Monitoring,Notification Service","Operations Team,Finance/Reconciliation Team,QA Team,DevOps Team,Business Team","Operational reporting and reconciliation changes can reduce traceability or delay incident detection.","Reconcile before and after release and confirm report completeness, alerting and operational runbooks.")
    );
    private DomainRule rule(String d,int w,String s,String m,String t,String r,String rec){return new DomainRule(d,w,split(s),list(m),list(t),r,rec);}
    private Set<String> split(String v){return new LinkedHashSet<>(Arrays.stream(v.split(",")).map(String::trim).toList());}
    private List<String> list(String v){return Arrays.stream(v.split(",")).map(String::trim).toList();}
    public Map<String,Object> analyse(String text){
        String normalized=text.toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim(); Set<String> hits=new LinkedHashSet<>(),domains=new LinkedHashSet<>(),modules=new LinkedHashSet<>(),teams=new LinkedHashSet<>(); List<String> reasons=new ArrayList<>(),recs=new ArrayList<>(); int score=12;
        for(DomainRule r:rules){List<String> matched=r.signals().stream().filter(s->contains(normalized,s)).toList();if(!matched.isEmpty()){domains.add(r.domain());modules.addAll(r.modules());teams.addAll(r.teams());matched.forEach(s->hits.add(s.toUpperCase(Locale.ROOT)));score+=r.weight();reasons.add(r.reason());recs.add(r.recommendation());}}
        boolean production=contains(normalized,"production")||contains(normalized,"deployment"), data=contains(normalized,"database")||contains(normalized,"migration"), customer=domains.stream().anyMatch(d->d.equals("Payments & settlement")||d.equals("Customer channels")||d.equals("Limits & transactions"));
        if(production){score+=8;hits.add("PRODUCTION");reasons.add("Production delivery needs a release window, monitoring and rollback readiness.");} if(data){score+=8;hits.add("DATA MIGRATION");modules.add("Database");teams.add("Database Team");reasons.add("Data changes need integrity validation, backup and recovery rehearsal.");} if(customer){score+=6;teams.add("Business Team");reasons.add("Customer-facing changes need communication, support readiness and journey validation.");}
        score=Math.min(score,100);String level=score>=75?"Critical":score>=55?"High":score>=30?"Medium":"Low",complexity=score>=75?"Very High":score>=55?"High":score>=30?"Medium":"Low";
        if(modules.isEmpty()){modules.addAll(List.of("Workflow Engine","Customer Profile","Audit Logs","Logging & Monitoring"));teams.addAll(List.of("Business Team","Backend Team","QA Team","Operations Team"));}if(domains.isEmpty())domains.add("General banking change governance");if(recs.isEmpty())recs.add("Confirm scope, accountable owner, success measures, approvals and rollback conditions before implementation.");
        Map<String,String> factors=new LinkedHashMap<>();
        factors.put("Customer impact", customer ? "Elevated" : "Controlled"); factors.put("API & integration", contains(normalized,"api") || modules.size()>4 ? "Elevated" : "Moderate");
        factors.put("Database & rollback", data ? "Elevated" : "Moderate"); factors.put("Compliance", domains.contains("Regulatory compliance") ? "High" : "Standard");
        factors.put("Security", domains.contains("Identity, fraud & security") ? "High" : "Standard"); factors.put("Payment operations", domains.contains("Payments & settlement") ? "High" : "Not directly affected");
        List<String> apis=new ArrayList<>(); if(contains(normalized,"upi")) apis.add("UPI Transaction API"); if(contains(normalized,"neft")||contains(normalized,"rtgs")||contains(normalized,"imps")) apis.add("Payment Orchestration API"); if(contains(normalized,"api")) apis.add("API Gateway / consumer contract"); if(apis.isEmpty()) apis.add("Service API contracts to be confirmed during solution design");
        List<String> tables=data ? List.of("customer_account", "transaction_ledger", "audit_event") : List.of("audit_event", "configuration_reference");
        Map<String,String> graph=new LinkedHashMap<>(); for(String module:modules.stream().limit(6).toList()) graph.put(module, module.equals("Core Banking") ? "Customer Profile, Transaction Validation, Audit Logs" : "API Gateway, Audit Logs, Logging & Monitoring");
        Map<String,Object> out=new LinkedHashMap<>();out.put("score",score);out.put("level",level);out.put("complexity",complexity);out.put("hits",new ArrayList<>(hits));out.put("domains",new ArrayList<>(domains));out.put("modules",new ArrayList<>(modules));out.put("teams",new ArrayList<>(teams));out.put("recommendations",recs);out.put("reasons",reasons);out.put("riskFactors",factors);out.put("apis",apis);out.put("tables",tables);out.put("graph",graph);out.put("developmentTime",time(complexity,true));out.put("testingTime",time(complexity,false));out.put("workflow",List.of("Business Analysis","Solution Design","Development","Code Review","QA","UAT","Deployment","Monitoring"));out.put("rollback",List.of("Approve a rollback decision owner and measurable rollback triggers.","Back up affected configuration and data before release.","Keep the prior application version, rule configuration and database migration reversal ready.","Reconcile transactions and notify operations if rollback is activated."));out.put("deploymentNotes",List.of("Deploy through a controlled environment with approved change window.","Run database/API compatibility checks and smoke tests before enabling traffic.","Monitor errors, latency, transaction success, reconciliation and fraud alerts after release.","Keep business, operations and support teams on release watch."));return out;
    }
    private boolean contains(String text,String signal){return Pattern.compile("(?<![a-z0-9])"+Pattern.quote(signal)+"(?![a-z0-9])").matcher(text).find();}
    private String time(String c,boolean dev){return switch(c){case "Very High"->dev?"3–4 Weeks":"1–2 Weeks";case "High"->dev?"1–2 Weeks":"4–6 Days";case "Medium"->dev?"3–5 Days":"2–3 Days";default->dev?"1–2 Days":"1 Day";};}
}
