package com.aurex.aurexbackend.service;

import com.aurex.aurexbackend.dto.AnalysisResponse;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Generates a downloadable PDF version of a completed AnalysisResponse.
 *
 * Built with PDFBox (already a project dependency, previously only used to
 * *read* uploaded PDFs in DocumentService - this is the missing "generate a
 * report" half of that dependency).
 *
 * No external service, no template engine - plain PDFBox content streams,
 * with manual pagination and word-wrap since PDFBox has no built-in layout
 * engine.
 */
@Service
public class ReportService {

    private static final float MARGIN = 50;
    private static final float PAGE_WIDTH = PDRectangle.A4.getWidth();
    private static final float PAGE_HEIGHT = PDRectangle.A4.getHeight();
    private static final float USABLE_WIDTH = PAGE_WIDTH - 2 * MARGIN;

    private static final PDType1Font HEADER_FONT = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
    private static final PDType1Font BODY_FONT = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
    private static final PDType1Font BODY_FONT_BOLD = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

    public byte[] generate(AnalysisResponse a) {
        try (PDDocument doc = new PDDocument()) {
            Cursor cursor = new Cursor(doc);

            cursor.brandHeader();
            cursor.title("Banking Change Analysis Report");
            cursor.metaLine("Generated by AUREX  ·  " + (a.getCreatedAt() != null
                    ? a.getCreatedAt().format(DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm"))
                    : "—"));
            cursor.spacer(14);

            cursor.sectionTitle("Request");
            cursor.paragraph(a.getTitle());
            cursor.spacer(10);

            cursor.sectionTitle("Executive Summary");
            cursor.paragraph(nvl(a.getExecutiveSummary(), a.getSummary()));
            cursor.spacer(10);

            cursor.keyValueRow(
                    "Risk Level", nvl(a.getRiskLevel(), "-"),
                    "Risk Score", a.getRiskScore() + "/100",
                    "Confidence", a.getConfidenceScore() + "%"
            );
            cursor.keyValueRow(
                    "Complexity", nvl(a.getEstimatedComplexity(), "-"),
                    "Dev Time", nvl(a.getEstimatedDevelopmentTime(), "-"),
                    "Testing Time", nvl(a.getEstimatedTestingTime(), "-")
            );
            cursor.spacer(10);

            cursor.sectionTitle("Impacted Modules");
            cursor.chipList(a.getImpactedModules());
            cursor.spacer(10);

            cursor.twoColumn("Business Impact", a.getBusinessImpact(), "Technical Impact", a.getTechnicalImpact());

            cursor.sectionTitle("Development Checklist");
            cursor.bulletList(a.getDevelopmentChecklist());
            cursor.spacer(6);

            cursor.sectionTitle("Testing Checklist");
            cursor.bulletList(a.getTestingChecklist());
            cursor.spacer(6);

            cursor.sectionTitle("Deployment Checklist");
            cursor.bulletList(a.getDeploymentChecklist());
            cursor.spacer(6);

            if (a.getRollbackPlan() != null && !a.getRollbackPlan().isEmpty()) {
                cursor.sectionTitle("Rollback Plan");
                cursor.bulletList(a.getRollbackPlan());
                cursor.spacer(6);
            }

            if (a.getRiskExplanation() != null && !a.getRiskExplanation().isEmpty()) {
                cursor.sectionTitle("Risk Explanation");
                for (Map.Entry<String, String> entry : a.getRiskExplanation().entrySet()) {
                    cursor.labeledParagraph(capitalize(entry.getKey()), entry.getValue());
                }
                cursor.spacer(6);
            }

            if (a.getEffort() != null && !a.getEffort().isEmpty()) {
                cursor.sectionTitle("Effort Estimate");
                for (Map.Entry<String, String> entry : a.getEffort().entrySet()) {
                    cursor.labeledParagraph(capitalize(entry.getKey()), entry.getValue());
                }
                cursor.spacer(6);
            }

            if (a.getRecommendations() != null && !a.getRecommendations().isEmpty()) {
                cursor.sectionTitle("Recommendations");
                cursor.bulletList(a.getRecommendations());
            }

            cursor.footer("AUREX  ·  Banking Change Intelligence  ·  " + nvl(a.getAnalysisSource(), "Banking Intelligence Engine"));
            cursor.close();

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            doc.save(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to generate PDF report", e);
        }
    }

    private static String nvl(String value, String fallback) {
        return (value == null || value.isBlank()) ? fallback : value;
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1).replaceAll("(?=[A-Z])", " ").trim();
    }

    /**
     * Small stateful helper that tracks the current page/Y position and
     * knows how to start a new page when content runs out of room. PDFBox
     * requires a brand new PDPageContentStream per page, so every drawing
     * method routes through here to stay page-break aware.
     */
    private static final class Cursor {
        private final PDDocument doc;
        private PDPage page;
        private PDPageContentStream stream;
        private float y;

        Cursor(PDDocument doc) throws IOException {
            this.doc = doc;
            newPage();
        }

        private void newPage() throws IOException {
            if (stream != null) stream.close();
            page = new PDPage(PDRectangle.A4);
            doc.addPage(page);
            stream = new PDPageContentStream(doc, page);
            y = PAGE_HEIGHT - MARGIN;
        }

        private void ensureRoom(float needed) throws IOException {
            if (y - needed < MARGIN + 20) {
                newPage();
            }
        }

        void brandHeader() throws IOException {
            stream.setNonStrokingColor(11 / 255f, 31 / 255f, 58 / 255f);
            stream.addRect(MARGIN, y - 4, USABLE_WIDTH, 4);
            stream.fill();
            y -= 24;
            stream.setNonStrokingColor(29 / 255f, 78 / 255f, 216 / 255f);
            stream.addRect(MARGIN, y - 13, 18, 18);
            stream.fill();
            stream.setNonStrokingColor(1, 1, 1);
            write(HEADER_FONT, 11, MARGIN + 4.2f, y - 1, "A");
            stream.setNonStrokingColor(0, 0, 0);
            write(HEADER_FONT, 14, MARGIN + 25, y, "AUREX");
            stream.setFont(BODY_FONT, 9);
            writeRightAligned(BODY_FONT, 9, PAGE_WIDTH - MARGIN, y + 2, "Banking Change Intelligence");
            y -= 20;
        }

        void title(String text) throws IOException {
            ensureRoom(30);
            write(HEADER_FONT, 18, MARGIN, y, text);
            y -= 22;
        }

        void metaLine(String text) throws IOException {
            ensureRoom(16);
            stream.setNonStrokingColor(90 / 255f, 100 / 255f, 115 / 255f);
            write(BODY_FONT, 9.5f, MARGIN, y, text);
            stream.setNonStrokingColor(0, 0, 0);
            y -= 16;
        }

        void sectionTitle(String text) throws IOException {
            ensureRoom(24);
            stream.setNonStrokingColor(29 / 255f, 78 / 255f, 216 / 255f);
            write(HEADER_FONT, 12, MARGIN, y, text.toUpperCase());
            stream.setNonStrokingColor(0, 0, 0);
            y -= 6;
            stream.setStrokingColor(228 / 255f, 233 / 255f, 241 / 255f);
            stream.moveTo(MARGIN, y);
            stream.lineTo(PAGE_WIDTH - MARGIN, y);
            stream.stroke();
            y -= 14;
        }

        void paragraph(String text) throws IOException {
            if (text == null || text.isBlank()) return;
            for (String line : wrap(text, BODY_FONT, 10.5f, USABLE_WIDTH)) {
                ensureRoom(15);
                write(BODY_FONT, 10.5f, MARGIN, y, line);
                y -= 15;
            }
        }

        void labeledParagraph(String label, String text) throws IOException {
            ensureRoom(15);
            write(BODY_FONT_BOLD, 10, MARGIN, y, label + ":");
            y -= 14;
            paragraph(text);
            y -= 4;
        }

        void bulletList(List<String> items) throws IOException {
            if (items == null || items.isEmpty()) {
                paragraph("None identified.");
                return;
            }
            for (String item : items) {
                List<String> lines = wrap(item, BODY_FONT, 10, USABLE_WIDTH - 14);
                for (int i = 0; i < lines.size(); i++) {
                    ensureRoom(14);
                    String prefix = i == 0 ? "•  " : "    ";
                    write(BODY_FONT, 10, MARGIN, y, prefix + lines.get(i));
                    y -= 14;
                }
            }
        }

        void chipList(List<String> items) throws IOException {
            if (items == null || items.isEmpty()) {
                paragraph("None identified.");
                return;
            }
            paragraph(String.join("   ·   ", items));
        }

        void keyValueRow(String... pairs) throws IOException {
            ensureRoom(18);
            float colWidth = USABLE_WIDTH / (pairs.length / 2);
            float x = MARGIN;
            for (int i = 0; i < pairs.length; i += 2) {
                stream.setNonStrokingColor(90 / 255f, 100 / 255f, 115 / 255f);
                write(BODY_FONT, 8.5f, x, y, pairs[i].toUpperCase());
                stream.setNonStrokingColor(0, 0, 0);
                write(BODY_FONT_BOLD, 11, x, y - 13, pairs[i + 1]);
                x += colWidth;
            }
            y -= 32;
        }

        void twoColumn(String leftTitle, List<String> left, String rightTitle, List<String> right) throws IOException {
            sectionTitle(leftTitle + "  /  " + rightTitle);
            float colWidth = (USABLE_WIDTH - 20) / 2;
            float startY = y;
            float leftX = MARGIN;
            float rightX = MARGIN + colWidth + 20;

            float leftEndY = renderColumn(left, leftX, colWidth);
            float afterLeftY = y;
            y = startY;
            float rightEndY = renderColumn(right, rightX, colWidth);

            y = Math.min(afterLeftY, y);
            y -= 6;
        }

        private float renderColumn(List<String> items, float x, float width) throws IOException {
            if (items == null || items.isEmpty()) {
                write(BODY_FONT, 10, x, y, "None identified.");
                y -= 14;
                return y;
            }
            for (String item : items) {
                for (String line : wrap(item, BODY_FONT, 9.5f, width - 12)) {
                    ensureRoom(13);
                    write(BODY_FONT, 9.5f, x, y, "- " + line);
                    y -= 13;
                }
            }
            return y;
        }

        void spacer(float amount) {
            y -= amount;
        }

        void footer(String text) throws IOException {
            stream.setNonStrokingColor(140 / 255f, 148 / 255f, 160 / 255f);
            write(BODY_FONT, 8, MARGIN, MARGIN - 10, text);
            stream.setNonStrokingColor(0, 0, 0);
        }

        void close() throws IOException {
            stream.close();
        }

        private void write(PDType1Font font, float size, float x, float yPos, String text) throws IOException {
            stream.beginText();
            stream.setFont(font, size);
            stream.newLineAtOffset(x, yPos);
            stream.showText(sanitize(text));
            stream.endText();
        }

        private void writeRightAligned(PDType1Font font, float size, float rightX, float yPos, String text) throws IOException {
            float width = font.getStringWidth(sanitize(text)) / 1000 * size;
            write(font, size, rightX - width, yPos, text);
        }

        private static String sanitize(String text) {
            if (text == null) return "";
            // WinAnsiEncoding (PDFBox's default for standard fonts) can't
            // encode arbitrary unicode - strip anything outside Latin-1 so
            // generation never throws on em-dashes, curly quotes, etc.
            StringBuilder sb = new StringBuilder();
            for (char c : text.toCharArray()) {
                if (c == '\u2014' || c == '\u2013') sb.append('-');
                else if (c == '\u2018' || c == '\u2019') sb.append('\'');
                else if (c == '\u201C' || c == '\u201D') sb.append('"');
                else if (c < 256) sb.append(c);
                else sb.append('?');
            }
            return sb.toString();
        }

        private static List<String> wrap(String text, PDType1Font font, float size, float maxWidth) throws IOException {
            List<String> lines = new ArrayList<>();
            if (text == null || text.isBlank()) return lines;
            String sanitized = sanitize(text);
            String[] words = sanitized.split("\\s+");
            StringBuilder current = new StringBuilder();
            for (String word : words) {
                String candidate = current.isEmpty() ? word : current + " " + word;
                float width = font.getStringWidth(candidate) / 1000 * size;
                if (width > maxWidth && !current.isEmpty()) {
                    lines.add(current.toString());
                    current = new StringBuilder(word);
                } else {
                    current = new StringBuilder(candidate);
                }
            }
            if (!current.isEmpty()) lines.add(current.toString());
            return lines;
        }
    }
}
